### ISSUE TITLE
Allow nested functions to receive parameters

### ISSUE THREAD

**Issue by robinvdvleuten** [baldwindavid/token_operator#1]
First of all thanks for this amazing library! It reduces so much boilerplate on our API routes. 

I am trying to do to following, but I am unsure if I'm running into an issue or trying to do something that isn't implemented;

```elixir
def list_users(opts \\ []) do
  Post
  |> TokenOperator.maybe(opts, :filter, name: &name/2)
end

def name(query, %{name: name}) do
from query, where: [name: ^name]
end
```

So I can call API routes like `/api/users?filter[name]=John` for example. But I don't get this working correctly.

**Comment by robinvdvleuten** [comment]
I've managed to solve it by using the following;

```elixir
def list_users(opts \\ []) do
    Form
    |> TokenOperator.maybe(opts, :filter, &maybe_filter_users/2)
    |> Repo.all()
  end

defp maybe_filter_forms(query, %{filter: filter}) do
  opts = Map.to_list(filter)
  TokenOperator.maybe(query, opts, :name, &name/2)
end

defp name(query, %{name: name}) do
  from(q in query, where: [name: ^name])
end
```

But it would be nice if the library supports it though!

**Comment by baldwindavid** [comment]
@robinvdvleuten Hey, I'm really sorry I missed notification of this issue. You may or may not be using the library anymore, but that should be doable with something like the following:

```elixir
def list_users(opts \\ []) do
  Post
  |> TokenOperator.maybe(opts, :filter, name: &name/2)
end

def name(query, %{filter: %{name: name}}) do
  from query, where: [name: ^name]
end
```

TokenOperator provides ALL the `opts` in the second argument rather than just those that might be under `filter`. It just converts that keyword list to a map for easy pattern-matching (ex. [pagination](https://github.com/baldwindavid/token_operator#example-pagination-via-single-function)). You can see the `opts` with...

```elixir
def name(query, %{filter: %{name: name}} = opts) do
  IO.inspect(opts)
  from query, where: [name: ^name]
end
```
